src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $category = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $publicationDate = null;

    #[ORM\Column]
    private ?bool $published = null;

    #[ORM\ManyToOne(inversedBy: 'books')]
    private ?Author $Author = null;

    #[ORM\ManyToMany(targetEntity: Reader::class, mappedBy: 'Book')]
    private Collection $readers;

    #[ORM\ManyToMany(targetEntity: Reader::class, inversedBy: 'books')]
    private Collection $Reader;

    public function __construct()
    {
        $this->readers = new ArrayCollection();
        $this->Reader = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getPublicationDate(): ?\DateTimeInterface
    {
        return $this->publicationDate;
    }

    public function setPublicationDate(\DateTimeInterface $publicationDate): static
    {
        $this->publicationDate = $publicationDate;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): static
    {
        $this->published = $published;

        return $this;
    }

    public function getAuthor(): ?Author
    {
        return $this->Author;
    }

    public function setAuthor(?Author $Author): static
    {
        $this->Author = $Author;

        return $this;
    }

    /**
     * @return Collection<int, Reader>
     */
    public function getReaders(): Collection
    {
        return $this->readers;
    }

    public function addReader(Reader $reader): static
    {
        if (!$this->readers->contains($reader)) {
            $this->readers->add($reader);
            $reader->addBook($this);
        }

        return $this;
    }

    public function removeReader(Reader $reader): static
    {
        if ($this->readers->removeElement($reader)) {
            $reader->removeBook($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Reader>
     */
    public function getReader(): Collection
    {
        return $this->Reader;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Author;
use App\Entity\Book;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('category',ChoiceType::class,[
                'choices'=>[
                    'Science-Fiction'=>'Science-Fiction',
                    'Mystery'=>'Mystery',
                    'Autobiography'=>'Autobiography'

                ]

            ])
            ->add('publicationDate')
            ->add('published')
            ->add('Author', EntityType::class, [
                'class'=>Author::class,
                'choice_label' => 'username',
            ])
            
        

            ->add('Ajouter',SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\BookRepository;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityManagerInterface;
use App\Form\SiwarType; 
use App\Form\SubmitType; 




use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class BookController extends AbstractController
{
    #[Route('/book', name: 'app_book')]
    public function index(): Response
    {
        return $this->render('book/index.html.twig', [
            'controller_name' => 'BookController',
        ]);
    }

    #[Route('/AjoutBook', name: 'AjoutBook')]
    public function AjoutBook(ManagerRegistry $managerRegistry,Request $req): Response
    {


        $x = $managerRegistry->getManager();
        $book = new Book();
        $form = $this->createForm(BookType::class,$book);
        $form->handleRequest($req);
        if($form->isSubmitted() and $form->isValid()){
            $x->persist($book);
            $x->flush();
            return $this->redirectToRoute('AffichageBook');
        }
        return $this->renderForm('book/AjoutBook.html.twig', [
            'n' => $form
        ]);
    }

    #[Route('/AffichageBook', name: 'AffichageBook')]
    public function AffichageBook(BookRepository $BookRepository ,EntityManagerInterface $entityManager,Request $req): Response
    {
    // Calculate the number of published books
    $publishedCount = $BookRepository->count(['published' => true]);
    // Calculate the number of unpublished books
    $unpublishedCount =$BookRepository->count(['published' => false]);


        $books = $BookRepository->findAll();
        
        
        $form = $this->createForm(SiwarType::class);
               $form->handleRequest($req);
       
               
                   $datainput = $form->get('id')->getData();
                   
                   $book= $BookRepository->findById($datainput); 
                    $books=$BookRepository->orderByAuthorName(); 
                    $books = $BookRepository->findBooksBeforeYearWithnbbooks();
       
              
       $shakespeareBooks = $BookRepository->updateCategoryForShakespeareBooks();
       
               foreach ($shakespeareBooks as $books) {
                   $books->setCategory('Romance');
               }
       
               $entityManager->flush();
       
       return $this->render('book/Affichagebook.html.twig', [
                   'books' => $books ,
                   'form' => $form->createView(),
                   'book'=>$book, 

                   'publishedCount' => $publishedCount,
            'unpublishedCount' => $unpublishedCount,
            'Affichage' => $books,
        ]);
    }
            










    

    #[Route('/ModifierBook/{id}', name: 'ModifierBook')]
    public function ModifierBook( BookRepository $BookRepository, ManagerRegistry $managerRegistry,Request $req,$id): Response
    {
        $x = $managerRegistry->getManager();
        $a = $BookRepository->find($id);
        $form = $this->createForm(BookType::class,$a);
        $form->handleRequest($req);
        if($form->isSubmitted() and $form->isValid()){
            $x->persist($a);
            $x->flush();
            return $this->redirectToRoute('AffichageBook');
        }
        return $this->renderForm('book/ModifierBook.html.twig', [
            'c' => $form
        ]);
    }

    #[Route('/SupprimerBook/{id}', name: 'SupprimerBook')]
    public function SupprimerBook(BookRepository $BookRepository, ManagerRegistry $managerRegistry,$id): Response
    {
        $x = $managerRegistry->getManager();
        $a = $BookRepository->find($id);
        $x->remove($a);
        $x->flush();
        return $this->redirectToRoute('AffichageBook');
    }
    #[Route('/bookPublished', name: 'bookPublished')]
    public function bookPublished(BookRepository $BookRepository): Response
    {
        $nbbookPub=$BookRepository->count(['published'=>true]);
        $nbbookUnpub=$BookRepository->count(['published'=>false]);
        return $this->render('book/AffichageBook.html.twig',[
            'nbbookPub'=>$nbbookPub,
            'nbbookUnpub'=>$nbbookUnpub,
        ]);
    }




    





}

templates/book/AffichageBook.html.twig
<!DOCTYPE html>
<html lang="en">
<body>
    <table border="3">
        <tr>
            <td>Title</td>
            <td>PublicationDate</td>
            <td>published</td>
            <td>Category</td>
            <td>Author</td>
            <td>Action</td>
            <td>Action</td>
            <td>Action</td>
        </tr> 
        
        
        
    <p> 
        Number of published books: {{ publishedCount }}
        <br>
        Number of unpublished books: {{ unpublishedCount }}
    </p>


        {% for i in Affichage %}
        <tr>
            
            <td>{{i.title}}</td>
            <td>{{i.getPublicationDate|date('Y-m-d')}}</td>
            <td>{{i.published}}</td>
            <td>{{i.category}}</td>
            <td>{{i.author.getUsername}}</td>
            <td><a href="{{path('ModifierBook',{'id':i.id})}}">Edit</a></td>
            <td><a href="{{path('SupprimerBook',{'id':i.id})}}">Delete</a></td>
             <td><a href="{{path('AffichageBook',{'id':i.id})}}">Show</a></td>


        </tr>
        {% endfor %}
    </table>
    <form action="{{ path('AjoutBook') }}">
        <button type="submit">Create New</button>
    </form>
</html>

templates/book/AjoutBook.html.twig
<h1>Add Book</h1>
{{form(n)}}

templates/book/ModifierBook.html.twig
{{form(c)}}

templates/book/bookDetails.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Book Details</h1>
    <dl>
        <dt>Title:</dt>
        <dd>{{ book.title }}</dd>
        <dt>Category:</dt>
        <dd>{{ book.category }}</dd>
        <dt>Publication Date:</dt>
        <dd>{{ book.publicationDate|date('Y-m-d') }}</dd>
        <dt>Published:</dt>
        <dd>{{ book.published ? 'Yes' : 'No' }}</dd>
        <dt>Author:</dt>
        <dd>{{ book.author.name }}</dd>
    </dl>
    <a href="{{ path('book_list') }}">Back to Book List</a>
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello BookController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/siwar/OneDrive/Bureau/Symfony/projet2/src/Controller/BookController.php'|file_link(0) }}">src/Controller/BookController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/siwar/OneDrive/Bureau/Symfony/projet2/templates/book/index.html.twig'|file_link(0) }}">templates/book/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/book/showDBbook.html.twig
<table border="3">
    <tr>
        <td>id</td>
        <td>title</td>
        <td>category</td>
        <td>publicationDate</td>
        <td>published</td>
    </tr>
    {% for a in books %}
    <tr>
        <td>{{a.id}}</td>
        <td>{{a.title| upper}}</td>
        <td>{{a.category}}</td>
         <td>{{ a.publicationDate.format('Y-m-d H:i:s') }}</td>
         <td>{{a.published}}</td>
    </tr>
    {% endfor %}
</table>

templates/book/showbookbyid.html.twig
{% if book is defined %}
<tr>
    
   
    
    <td>id</td>
        <td>title</td>
        <td>category</td>
        <td>publicationDate</td>
        <td>published</td>

</tr>
    <tr>
        <td>{{book.id}}</td>
        <td>{{book.title| upper}}</td>
        <td>{{book.category}}</td>
         <td>{{ b.publicationDate.format('Y-m-d H:i:s') }}</td>
         <td>{{book.published}}</td>
    </tr>
{% else %}
    <p>Livre introuvable</p>
{% endif %}

templates/book/sum.html.twig
{% block content %}
    <h1>Somme des livres de la catégorie "Science Fiction"</h1>
    <p>La somme est : {{ sum }}</p>
{% endblock %}